#docker compose up -d

version: '3.8'
services:
  gameapp-database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: gameapp-database
    ports:
      - '3309:3306'
    environment:
      - MYSQL_DATABASE=gameapp
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER= root
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local